version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "transactions_risk_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "boss"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      POSTGRES_HOST: "postgres"

volumes:
  db:

networks:
  network: